# Generated by Django 5.0.4 on 2024-05-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('count', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='Product_photos/%y/%m/%d')),
                ('status', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, choices=[('Medicine', 'Medicine'), ('Equipment', 'Equipment'), ('Vitamins', 'Vitamins')], max_length=50, null=True)),
            ],
        ),
    ]
