# Generated by Django 5.0.4 on 2024-05-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_alter_client_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
        migrations.RemoveField(
            model_name='client',
            name='phonenumber',
        ),
    ]
