# Generated by Django 5.0.4 on 2024-05-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
