# Generated by Django 5.0.4 on 2024-05-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
