# Generated by Django 5.0.4 on 2024-05-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_product_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='category',
            field=models.CharField(blank=True, choices=[('Medicine', 'Medicine'), ('Equipment', 'Equipment'), ('Vitamins', 'Vitamins')], max_length=50, null=True),
        ),
    ]
